import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { auth } from "@/lib/auth";
import { SignInCard } from "@/components/auth/signin";

import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const noSession = !session || session?.error === "RefreshTokenError"
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased", geistSans.variable, geistMono.variable)}

      >
        {noSession ?
          <div className="w-full h-screen flex flex-col justify-center items-center">
            <SignInCard />
          </div> :
          <>

            <div vaul-drawer-wrapper="">
              <div className="relative flex min-h-screen flex-col bg-background max-w-screen-xl mx-auto">
                {children}
              </div>
            </div>
          </>
        }
      </body>
    </html>
  );
}
